#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

branch="$(git symbolic-ref --short -q HEAD)"

if [ "$branch" = "main" ]; then
  echo "${RED} You are on main branch"
  echo "You can't commit directly to master branch"
  exit 1
fi