#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

local_branch_name="$(git rev-parse --abbrev-ref HEAD)"

valid_branch_regex='^((hotfix|bugfix|feature)\/[a-zA-Z0-9\-]+)$'

message="Please check your branch name."
GREEN='\033[0;32m'

if [[ ! $local_branch_name =~ $valid_branch_regex ]]; then
    echo -e "\033[0;31m$message"
    exit 1
fi

npm run test -- -silent

echo ""
echo "${GREEN}------------------"
echo "${GREEN}Husky pre-push: All Test OK."
echo "${GREEN}------------------"
NC='\033[0m'
echo "${NC}Continuing with git push..."
echo ""
echo ""

exit 0
